{{ if (.Values.externalController).url }}
---
{{- $url := urlParse .Values.externalController.url -}}
{{- $proto := regexSplit ":" (get $url "scheme") -1 -}}
{{- $host := regexSplit ":" (get $url "host") -1 -}}
{{- $addr := index $host 0 -}}
{{- $port := index $host 1 }}
{{- if (regexMatch "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\\b){4}$" $host) -}}
{{-   $addrType := "IPv4" -}}
{{- else -}}
{{-   $addrType := "FQDN" -}}
{{- end -}}
apiVersion: v1
kind: EndpointSlice
metadata:
  name: {{ include "piraeus-operator.fullname" . }}-external-controller-metrics-service
  labels:
  {{- include "piraeus-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: linstor-external-controller
    kubernetes.io/service-name: {{ include "piraeus-operator.fullname" . }}-external-controller-metrics-service
addressType: {{ $addrType }}
ports:
  - name: metrics
    port: {{ $port }}
    appProtocol: {{ $proto }}
    protocol: TCP
endpoints:
  - addresses:
    - {{ $addr }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "piraeus-operator.fullname" . }}-external-controller-metrics-service
  labels:
  {{- include "piraeus-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: linstor-external-controller
spec:
  ports:
    - name: metrics
      port: {{ $port }}
      targetPort: {{ $port }}
{{ end }}
